{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "#storing images in local host\n",
    "from pymongo import MongoClient\n",
    "import os\n",
    "# Connect to the server with the hostName and portNumber.\n",
    "connection = MongoClient(\"localhost\", 27017)\n",
    "\n",
    "# Connect to the Database where the images will be stored.\n",
    "database = connection['Images']\n",
    "import gridfs\n",
    "\n",
    "#Create an object of GridFs for the above database.\n",
    "fs = gridfs.GridFS(database)\n",
    "\n",
    "#define an image object with the location.\n",
    "path = 'Path where the files located i.e. Images'\n",
    "List = os.listdir(path)\n",
    "Images=list(List)\n",
    "for i in range(len(Images)):\n",
    "    name=Images[i][0:10]\n",
    "    file = path+Images[i]\n",
    "    col = database[\"fs.files\"] \n",
    "    temp=1\n",
    "    try:\n",
    "        for i in col.find():\n",
    "            if (name in i.values()):\n",
    "                raise Exception(\"Image Already Found\")\n",
    "    except:\n",
    "        temp=0\n",
    "        print(name,\" Image Already Found\")\n",
    "    #Open the image in read-only format.\n",
    "    if(temp==1):\n",
    "        with open(file, 'rb') as f:\n",
    "            contents = f.read()\n",
    "    \n",
    "    #Now store/put the image via GridFs object.\n",
    "        fs.put(contents, filename=name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-5-44e16818449b>, line 13)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-5-44e16818449b>\"\u001b[1;36m, line \u001b[1;32m13\u001b[0m\n\u001b[1;33m    path = 'Path where the files located i.e. Images'.\u001b[0m\n\u001b[1;37m                                                      ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "#storing images in atlas cluster\n",
    "import pymongo\n",
    "import os\n",
    "import gridfs\n",
    "password=input(\"Enter Password\")\n",
    "connection = pymongo.MongoClient('Atlas MongoDB url')\n",
    "# Connect to the server with the hostName and portNumber.\n",
    "database = connection['Images']\n",
    "#Create an object of GridFs for the above database.\n",
    "fs = gridfs.GridFS(database)\n",
    "\n",
    "#define an image object with the location.\n",
    "path = 'Path where the files located i.e. Images'\n",
    "List = os.listdir(path)\n",
    "Images=list(List)\n",
    "for i in range(len(Images)):\n",
    "    name=Images[i][0:10]\n",
    "    file = path+Images[i]\n",
    "    col = database[\"fs.files\"] \n",
    "    temp=1\n",
    "    try:\n",
    "        for i in col.find():\n",
    "            if (name in i.values()):\n",
    "                raise Exception(\"Image Already Found\")\n",
    "    except:\n",
    "        temp=0\n",
    "        print(name,\" Image Already Found\")\n",
    "    #Open the image in read-only format.\n",
    "    if(temp==1):\n",
    "        with open(file, 'rb') as f:\n",
    "            contents = f.read()\n",
    "    \n",
    "    #Now store/put the image via GridFs object.\n",
    "        fs.put(contents, filename=name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter Username Balu\n",
      "Enter Password Prem\n"
     ]
    },
    {
     "ename": "ConfigurationError",
     "evalue": "The \"dnspython\" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv extra:\n C:\\ProgramData\\Anaconda3\\envs\\virtualenv\\python.exe -m pip install \"pymongo[srv]\"",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mConfigurationError\u001b[0m                        Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-6-13838b86ab72>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[0musername\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0minput\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'Enter Username '\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mpassword\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0minput\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Enter Password \"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 7\u001b[1;33m \u001b[0mconnection\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpymongo\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mMongoClient\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'mongodb+srv://'\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0musername\u001b[0m\u001b[1;33m+\u001b[0m\u001b[1;34m':'\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0mpassword\u001b[0m\u001b[1;33m+\u001b[0m\u001b[1;34m'@cluster0.f58i3.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      8\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mconnection\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\virtualenv\\lib\\site-packages\\pymongo\\mongo_client.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, host, port, document_class, tz_aware, connect, type_registry, **kwargs)\u001b[0m\n\u001b[0;32m    670\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0misinstance\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mport\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    671\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"port must be an instance of int\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 672\u001b[1;33m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    673\u001b[0m         \u001b[1;31m# _pool_class, _monitor_class, and _condition_class are for deep\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    674\u001b[0m         \u001b[1;31m# customization of PyMongo, e.g. Motor.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\virtualenv\\lib\\site-packages\\pymongo\\uri_parser.py\u001b[0m in \u001b[0;36mparse_uri\u001b[1;34m(uri, default_port, validate, warn, normalize, connect_timeout)\u001b[0m\n\u001b[0;32m    451\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    452\u001b[0m     \u001b[1;33m.\u001b[0m\u001b[1;33m.\u001b[0m \u001b[0mversionchanged\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m3.6\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 453\u001b[1;33m         \u001b[0mAdded\u001b[0m \u001b[0msupport\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mmongodb\u001b[0m\u001b[1;33m+\u001b[0m\u001b[0msrv\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m//\u001b[0m \u001b[0mURIs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    454\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    455\u001b[0m     \u001b[1;33m.\u001b[0m\u001b[1;33m.\u001b[0m \u001b[0mversionchanged\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m:\u001b[0m \u001b[1;36m3.5\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mConfigurationError\u001b[0m: The \"dnspython\" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv extra:\n C:\\ProgramData\\Anaconda3\\envs\\virtualenv\\python.exe -m pip install \"pymongo[srv]\""
     ]
    }
   ],
   "source": [
    "#Example \n",
    "import pymongo\n",
    "import os\n",
    "import gridfs\n",
    "username=input('Enter Username ')\n",
    "password=input(\"Enter Password \")\n",
    "connection = pymongo.MongoClient('mongodb+srv://'+username+':'+password+'@cluster0.f58i3.mongodb.net/myFirstDatabase?retryWrites=true&w=majority')\n",
    "print(connection)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
